# Generated by Django 4.0.1 on 2022-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_date_creation_movie_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_creation',
            field=models.DateTimeField(verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_update',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie_app.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Movie name'),
        ),
    ]
