# Generated by Django 4.0.1 on 2022-01-28 06:16

from django.db import migrations, models
import movie_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_menuitem_alter_movie_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='position',
            field=models.PositiveIntegerField(default=movie_app.models.auto_incrementor),
        ),
    ]
