# Generated by Django 4.0.1 on 2022-01-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_menuitem_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact us message',
                'verbose_name_plural': 'Contact us messages',
                'ordering': ('name',),
            },
        ),
    ]
